spring:
  datasource:
    url: jdbc:h2:mem:local;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password:
logging:
  level:
    root: debug
mybatis:
  mapper-locations: "classpath:/mappers/**/*Mapper.xml"

