spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: tester
    password:
logging:
  level:
    root: debug
mybatis:
  mapper-locations: "classpath:/mappers/**/*Mapper.xml"

